// -----------------------------------------------------------------------
// <copyright file="OnnxCrossEncoderScorerTests.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using Xunit;

namespace Netclaw.Embeddings.Tests;

/// <summary>
/// Exercises <see cref="OnnxCrossEncoderScorer"/> against the tiny fixture graph committed at
/// <c>Fixtures/tiny-cross-encoder.onnx</c> / <c>Fixtures/tiny-cross-encoder-vocab.txt</c>
/// (generated by <c>Fixtures/generate_fixture_cross_encoder.py</c> — see that file's header
/// comment for the graph shape, why it multiplies a per-segment scale into each word embedding
/// rather than adding one, and why every hand-computed expected value below is exact for a
/// single-dimension embedding). No network access; this is the CI-safe substitute for the real
/// 22 MB allowlisted <c>Xenova/ms-marco-MiniLM-L-6-v2</c> model (memory-relevance-gate task 2.5).
/// </summary>
public sealed class OnnxCrossEncoderScorerTests : IAsyncLifetime
{
    private const string ModelId = "tiny-cross-encoder-fixture";

    private OnnxCrossEncoderScorer _scorer = null!;
    private long _relevantTokenId;

    public async ValueTask InitializeAsync()
    {
        var fixturesDir = Path.Combine(AppContext.BaseDirectory, "Fixtures");
        var vocabPath = Path.Combine(fixturesDir, "tiny-cross-encoder-vocab.txt");
        _scorer = await OnnxCrossEncoderScorer.LoadAsync(
            modelPath: Path.Combine(fixturesDir, "tiny-cross-encoder.onnx"),
            vocabPath: vocabPath,
            modelId: ModelId,
            maxConcurrency: 2);

        // FastBertTokenizer assigns ids by vocab.txt line number, so this is a robust, direct
        // way to know "relevant"'s id without relying on any encode side-channel.
        var vocabLines = File.ReadAllLines(vocabPath);
        _relevantTokenId = Array.IndexOf(vocabLines, "relevant");
        Assert.True(_relevantTokenId >= 0, "fixture vocab must contain 'relevant'");
    }

    public ValueTask DisposeAsync()
    {
        _scorer.Dispose();
        return ValueTask.CompletedTask;
    }

    [Fact]
    public void Loaded_scorer_reports_its_identity()
    {
        Assert.Equal(ModelId, _scorer.ModelId);
        Assert.True(_scorer.IsAvailable);
    }

    // ── Sigmoid + batch scoring (task 1.2, 2.5) ────────────────────────────
    //
    // The fixture's single-dimension embeddings make every logit hand-computable: "relevant" and
    // "answer" both embed to 10.0, "irrelevant" to -10.0, everything else (fillers, special
    // tokens) to 0.0. Query-segment (type 0) positions keep a word's value unscaled; candidate-
    // segment (type 1) positions double it. Pooling is an attention-masked mean over every
    // position (CLS + query + SEP + candidate + SEP), so e.g. "[CLS] relevant [SEP] relevant
    // [SEP]" (5 tokens) sums to 10*1 (query "relevant") + 10*2 (candidate "relevant") = 30,
    // mean 30/5 = 6.0, sigmoid(6.0) ≈ 0.9975.

    [Fact]
    public async Task ScoreAsync_matches_the_hand_computed_sigmoid_for_a_matching_pair()
    {
        var scores = await _scorer.ScoreAsync("relevant", ["relevant"], TestContext.Current.CancellationToken);

        var expected = Sigmoid(6.0); // (10*1 + 10*2) / 5
        Assert.Equal(expected, scores[0], precision: 5);
    }

    [Fact]
    public async Task ScoreAsync_matches_the_hand_computed_sigmoid_for_an_unhelpful_pair()
    {
        var scores = await _scorer.ScoreAsync("relevant", ["irrelevant"], TestContext.Current.CancellationToken);

        var expected = Sigmoid(-2.0); // (10*1 + (-10)*2) / 5
        Assert.Equal(expected, scores[0], precision: 5);
    }

    [Fact]
    public async Task ScoreAsync_preserves_candidate_order_in_a_batch()
    {
        string[] candidates = ["irrelevant", "relevant", "filler"];

        var scores = await _scorer.ScoreAsync("relevant", candidates, TestContext.Current.CancellationToken);

        Assert.Equal(3, scores.Count);
        var single0 = await _scorer.ScoreAsync("relevant", [candidates[0]], TestContext.Current.CancellationToken);
        var single1 = await _scorer.ScoreAsync("relevant", [candidates[1]], TestContext.Current.CancellationToken);
        var single2 = await _scorer.ScoreAsync("relevant", [candidates[2]], TestContext.Current.CancellationToken);
        Assert.Equal(single0[0], scores[0], precision: 6);
        Assert.Equal(single1[0], scores[1], precision: 6);
        Assert.Equal(single2[0], scores[2], precision: 6);
    }

    [Fact]
    public async Task ScoreAsync_of_empty_candidates_returns_empty_without_scoring()
    {
        var scores = await _scorer.ScoreAsync("relevant", [], TestContext.Current.CancellationToken);
        Assert.Empty(scores);
    }

    // ── Pair-encoding correctness: token_type_ids (task 1.2, 2.5) ──────────
    //
    // EncodePair is internal (InternalsVisibleTo) specifically so these scenarios can assert on
    // the exact assembled arrays rather than needing a live ONNX Run per case.

    [Fact]
    public void EncodePair_assembles_CLS_query_SEP_candidate_SEP_with_correct_token_type_ids()
    {
        var (ids, mask, types, length) = _scorer.EncodePair("relevant", "filler");

        // [CLS] relevant [SEP] filler [SEP] -- 5 real tokens, bucketed to 8.
        Assert.Equal(8, length);
        Assert.Equal([1, 1, 1, 1, 1, 0, 0, 0], mask);
        Assert.Equal([0, 0, 0, 1, 1, 0, 0, 0], types);

        // ids[2] is [SEP] closing the query segment; ids[4] is the SAME [SEP] id reused to close
        // the candidate segment (one shared special-token id, two positions).
        Assert.Equal(ids[2], ids[4]);
        Assert.NotEqual(ids[0], ids[2]); // [CLS] and [SEP] are different vocab ids
        Assert.NotEqual(ids[1], ids[3]); // "relevant" vs "filler" are different vocab ids
    }

    [Fact]
    public void EncodePair_swapping_query_and_candidate_changes_which_position_carries_the_word()
    {
        var forward = _scorer.EncodePair("relevant", "filler");
        var swapped = _scorer.EncodePair("filler", "relevant");

        // Same structural shape (both single-word/single-word pairs)...
        Assert.Equal(forward.Length, swapped.Length);
        Assert.Equal(forward.Types, swapped.Types);

        // ...but the token id sequence differs: "relevant" sits at the query position (index 1)
        // in the first pair and at the candidate position (index 3) in the second.
        Assert.Equal(forward.Ids[1], swapped.Ids[3]);
        Assert.Equal(forward.Ids[3], swapped.Ids[1]);
        Assert.NotEqual(forward.Ids, swapped.Ids);
    }

    // ── Pair-encoding correctness: only_second truncation (task 1.2, 2.5) ──

    [Fact]
    public void EncodePair_truncates_the_candidate_never_the_query()
    {
        // Query alone would need every position under a plain single-sequence encode if it were
        // long enough to matter here; what this test actually pins is the shoot-out's contract:
        // an over-budget candidate loses tokens, the query never does.
        var query = "the cat sat on the mat"; // 6 content tokens, comfortably short
        var longCandidate = string.Join(' ', Enumerable.Repeat("filler", 600));

        var (_, mask, _, length) = _scorer.EncodePair(query, longCandidate);

        Assert.True(length <= 512, $"expected the pair to respect MaxTokens, got {length}");
        // 1x[CLS] + 6 query tokens + 1x[SEP] fit entirely -- none of the query's own tokens are
        // ever dropped, regardless of how long the candidate is.
        Assert.Equal(6, mask.Skip(1).Take(6).Count(m => m == 1));
    }

    [Fact]
    public void EncodePair_drops_a_candidate_marker_word_placed_at_the_end_of_an_over_budget_candidate()
    {
        var query = "the";
        var candidateMarkerAtEnd = string.Join(' ', Enumerable.Repeat("filler", 600)) + " relevant";

        var (ids, _, _, _) = _scorer.EncodePair(query, candidateMarkerAtEnd);

        // only_second truncation keeps the candidate's PREFIX and drops its suffix -- "relevant"
        // was the very last content token, so it must not survive into the assembled pair.
        Assert.DoesNotContain(_relevantTokenId, ids);
    }

    [Fact]
    public void EncodePair_keeps_a_candidate_marker_word_placed_at_the_start_of_an_over_budget_candidate()
    {
        var query = "the";
        var candidateMarkerAtStart = "relevant " + string.Join(' ', Enumerable.Repeat("filler", 600));

        var (ids, _, _, _) = _scorer.EncodePair(query, candidateMarkerAtStart);

        // The marker was the candidate's FIRST content token, so only_second truncation (which
        // keeps the prefix) must retain it even though the overall candidate was truncated.
        Assert.Contains(_relevantTokenId, ids);
    }

    // ── Pair-encoding correctness: dynamic length bucketing (task 1.2, 2.5) ─

    [Fact]
    public void EncodePair_pads_the_assembled_length_up_to_a_bucket_of_8()
    {
        // "the cat" (2 content) + "sat on mat" (3 content): 1+2+1+3+1 = 8 raw tokens exactly --
        // must NOT be bumped to the next bucket (16).
        var exact = _scorer.EncodePair("the cat", "sat on mat");
        Assert.Equal(8, exact.Length);

        // "relevant" (1) + "filler" (1): 1+1+1+1+1 = 5 raw tokens -- rounds up to 8.
        var shortPair = _scorer.EncodePair("relevant", "filler");
        Assert.Equal(8, shortPair.Length);
    }

    private static double Sigmoid(double logit) => 1.0 / (1.0 + Math.Exp(-logit));
}
