// -----------------------------------------------------------------------
// <copyright file="OnnxMemoryEmbedderTests.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using Netclaw.Actors.Memory;
using Xunit;

namespace Netclaw.Embeddings.Tests;

/// <summary>
/// Exercises <see cref="OnnxMemoryEmbedder"/> against the tiny fixture graph committed at
/// <c>Fixtures/tiny-embedder.onnx</c> / <c>Fixtures/tiny-vocab.txt</c> (generated by
/// <c>Fixtures/generate_fixture_model.py</c> — see that file's header comment for the graph
/// shape and why it mean-pools instead of doing a plain CLS passthrough). No network access;
/// this is the CI-safe substitute for the real ~110M/~335M-parameter allowlisted models.
/// </summary>
public sealed class OnnxMemoryEmbedderTests : IAsyncLifetime
{
    private const string ModelId = "tiny-fixture";
    private const int Dimensions = 8;

    // memory-query-prefix design D2/D3 fixture prefix — not a real model card string, just an
    // exercisable prefix for OnnxMemoryEmbedderTests.QueryPrefix-specific facts below. _embedder
    // (no prefix) covers every pre-existing fact in this file unchanged; _prefixedEmbedder is
    // used only by the purpose-application facts.
    private const string FixtureQueryPrefix = "search_query: ";

    private OnnxMemoryEmbedder _embedder = null!;
    private OnnxMemoryEmbedder _prefixedEmbedder = null!;

    public async ValueTask InitializeAsync()
    {
        var fixturesDir = Path.Combine(AppContext.BaseDirectory, "Fixtures");
        _embedder = await OnnxMemoryEmbedder.LoadAsync(
            modelPath: Path.Combine(fixturesDir, "tiny-embedder.onnx"),
            vocabPath: Path.Combine(fixturesDir, "tiny-vocab.txt"),
            modelId: ModelId,
            dimensions: Dimensions,
            queryPrefix: "",
            maxConcurrency: 2);
        _prefixedEmbedder = await OnnxMemoryEmbedder.LoadAsync(
            modelPath: Path.Combine(fixturesDir, "tiny-embedder.onnx"),
            vocabPath: Path.Combine(fixturesDir, "tiny-vocab.txt"),
            modelId: ModelId,
            dimensions: Dimensions,
            queryPrefix: FixtureQueryPrefix,
            maxConcurrency: 2);
    }

    public ValueTask DisposeAsync()
    {
        _embedder.Dispose();
        _prefixedEmbedder.Dispose();
        return ValueTask.CompletedTask;
    }

    [Fact]
    public void Loaded_embedder_reports_its_identity()
    {
        Assert.Equal(ModelId, _embedder.ModelId);
        Assert.Equal(Dimensions, _embedder.Dimensions);
        Assert.True(_embedder.IsAvailable);
    }

    [Fact]
    public async Task EmbedAsync_is_deterministic_for_the_same_text()
    {
        var v1 = await _embedder.EmbedAsync("cat sat on the mat", EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
        var v2 = await _embedder.EmbedAsync("cat sat on the mat", EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);

        Assert.Equal(v1.ToArray(), v2.ToArray());
    }

    [Fact]
    public async Task EmbedAsync_produces_L2_normalized_vectors_of_the_declared_dimension()
    {
        var vector = await _embedder.EmbedAsync("hello world", EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);

        Assert.Equal(Dimensions, vector.Length);
        var normSquared = vector.ToArray().Sum(x => (double)x * x);
        Assert.True(Math.Abs(normSquared - 1.0) < 1e-4, $"expected unit-length vector, got ||v||^2={normSquared}");
    }

    [Fact]
    public async Task EmbedAsync_reflects_the_input_text_not_just_the_CLS_token()
    {
        // The fixture's mean-pooling graph (see its header comment) makes the output depend on
        // every real token, not just position 0 — so different inputs must not collapse to
        // the same vector the way a naive CLS-only passthrough over an un-contextualized
        // Gather would.
        var v1 = await _embedder.EmbedAsync("cat sat on the mat", EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
        var v2 = await _embedder.EmbedAsync("quarterly revenue grew", EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);

        Assert.NotEqual(v1.ToArray(), v2.ToArray());
    }

    [Fact]
    public async Task EmbedBatchAsync_preserves_input_order()
    {
        string[] texts = ["hello world", "cat sat", "dog running", "quarterly revenue grew by percent"];

        var batch = await _embedder.EmbedBatchAsync(texts, EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);

        Assert.Equal(texts.Length, batch.Count);
        for (var i = 0; i < texts.Length; i++)
        {
            var single = await _embedder.EmbedAsync(texts[i], EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
            Assert.Equal(single.ToArray(), batch[i].ToArray());
        }
    }

    [Fact]
    public async Task EmbedBatchAsync_of_empty_input_returns_empty()
    {
        var batch = await _embedder.EmbedBatchAsync([], EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
        Assert.Empty(batch);
    }

    // ── Dynamic-length padding (memory-core-redesign Slice 4, design D6 mitigation) ──
    //
    // OnnxMemoryEmbedder.EmbedOne now pads each input to bucket-of-8(actual token count)
    // instead of always the fixed 512-token scratch buffers (tools/embed-latency-bench measured
    // 1.000000 cosine parity vs fixed-512 across 10 fixed sentences on the real allowlisted
    // model). There is no production hook to force the OLD fixed-512 behavior for a literal
    // side-by-side cosine comparison here (adding one purely for this test would be exactly the
    // kind of test-only production surface the constitution's "no optional params for test
    // convenience" rule warns against), so these tests instead pin the properties that a broken
    // bucketing implementation (wrong slice length, stale mask, truncation bug) would violate:
    // determinism, correct/declared dimensionality, and a valid unit-length vector, across
    // several distinctly-lengthed inputs so short, medium, and near-full-bucket lengths are all
    // exercised through the real bucketing path.
    [Theory]
    [InlineData("cat")]
    [InlineData("cat sat on the mat")]
    [InlineData("the quarterly revenue report shows strong growth across every regional market segment this year")]
    public async Task EmbedAsync_with_dynamic_length_padding_is_deterministic_and_normalized(string text)
    {
        var v1 = await _embedder.EmbedAsync(text, EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
        var v2 = await _embedder.EmbedAsync(text, EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);

        Assert.Equal(v1.ToArray(), v2.ToArray());
        Assert.Equal(Dimensions, v1.Length);

        var normSquared = v1.ToArray().Sum(x => (double)x * x);
        Assert.True(Math.Abs(normSquared - 1.0) < 1e-4, $"expected unit-length vector for \"{text}\", got ||v||^2={normSquared}");
    }

    [Theory]
    [InlineData(0, 8)]
    [InlineData(1, 8)]
    [InlineData(8, 8)]
    [InlineData(9, 16)]
    [InlineData(16, 16)]
    [InlineData(17, 24)]
    [InlineData(511, 512)]
    [InlineData(512, 512)]
    public void ComputeBucketedLength_rounds_up_to_the_nearest_bucket_of_8(int actualTokenCount, int expectedBucketLength)
    {
        Assert.Equal(expectedBucketLength, OnnxMemoryEmbedder.ComputeBucketedLength(actualTokenCount));
    }

    // ── Query prefix (memory-query-prefix design D1/D2, tasks 1.3/2.4) ──

    /// <summary>
    /// Byte-compat regression guard: this is the EXACT vector <c>OnnxMemoryEmbedder.EmbedOne</c>
    /// produced for this text against this fixture model on the commit immediately before the
    /// purpose-aware seam landed (captured by temporarily instrumenting the pre-change code —
    /// see the memory-query-prefix change's task notes). Passage-purpose embedding must remain
    /// byte-identical after adding the query-prefix seam: adopting a prefix for
    /// <see cref="EmbeddingPurpose.RetrievalQuery"/> must never re-derive a single stored
    /// document vector.
    /// </summary>
    [Fact]
    public async Task Passage_purpose_embedding_is_byte_identical_to_the_pre_prefix_seam()
    {
        float[] expected =
        [
            0.27457318f, 0.29614678f, 0.31772035f, 0.339294f,
            0.36086756f, 0.3824412f, 0.4040148f, 0.42558837f,
        ];

        var vector = await _embedder.EmbedAsync(
            "Netclaw memory-query-prefix regression fixture text", EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);

        Assert.Equal(expected, vector.ToArray());
    }

    [Fact]
    public async Task RetrievalQuery_purpose_applies_the_embedders_configured_prefix()
    {
        const string text = "Netclaw memory-query-prefix regression fixture text";

        var passageVector = await _prefixedEmbedder.EmbedAsync(text, EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
        var queryVector = await _prefixedEmbedder.EmbedAsync(text, EmbeddingPurpose.RetrievalQuery, TestContext.Current.CancellationToken);

        // Same text, same embedder instance, different purpose -- the prefix is applied for
        // RetrievalQuery only, so the two vectors must differ.
        Assert.NotEqual(passageVector.ToArray(), queryVector.ToArray());
    }

    [Fact]
    public async Task Passage_purpose_ignores_the_embedders_configured_prefix()
    {
        // _prefixedEmbedder has a real, non-empty QueryPrefix, but Passage purpose must produce
        // the exact same vector as an embedder with NO prefix at all -- this is what keeps
        // document-side vectors byte-identical regardless of which model's prefix is active.
        const string text = "cat sat on the mat";

        var fromUnprefixedEmbedder = await _embedder.EmbedAsync(text, EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
        var fromPrefixedEmbedder = await _prefixedEmbedder.EmbedAsync(text, EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);

        Assert.Equal(fromUnprefixedEmbedder.ToArray(), fromPrefixedEmbedder.ToArray());
    }

    [Fact]
    public async Task RetrievalQuery_purpose_is_a_no_op_when_the_embedder_has_no_configured_prefix()
    {
        const string text = "cat sat on the mat";

        var passageVector = await _embedder.EmbedAsync(text, EmbeddingPurpose.Passage, TestContext.Current.CancellationToken);
        var queryVector = await _embedder.EmbedAsync(text, EmbeddingPurpose.RetrievalQuery, TestContext.Current.CancellationToken);

        Assert.Equal(passageVector.ToArray(), queryVector.ToArray());
    }
}
