// -----------------------------------------------------------------------
// <copyright file="McpShadowCatalogWriter.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using System.Text;
using Microsoft.Extensions.Logging;
using Netclaw.Actors.Tools;
using Netclaw.Configuration;
using Netclaw.Tools;

namespace Netclaw.Daemon.Mcp;

/// <summary>
/// Writes system-managed MCP shadow catalogs to disk for progressive disclosure.
/// </summary>
internal sealed class McpShadowCatalogWriter
{
    private readonly NetclawPaths _paths;
    private readonly ToolRegistry _toolRegistry;
    private readonly ILogger<McpShadowCatalogWriter> _logger;

    public McpShadowCatalogWriter(
        NetclawPaths paths,
        ToolRegistry toolRegistry,
        ILogger<McpShadowCatalogWriter> logger)
    {
        _paths = paths;
        _toolRegistry = toolRegistry;
        _logger = logger;
    }

    public string WriteCatalogs()
    {
        Directory.CreateDirectory(_paths.ToolingShadowDirectory);
        Directory.CreateDirectory(_paths.McpShadowDirectory);

        var summaries = _toolRegistry.GetMcpServerSummaries();

        var keepFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var summary in summaries)
        {
            var fileName = ToSafeFileName(summary.ServerName) + ".md";
            var filePath = Path.Combine(_paths.McpShadowDirectory, fileName);
            var tools = _toolRegistry.GetToolsForServer(new McpServerName(summary.ServerName), int.MaxValue);

            var content = BuildServerCatalog(summary, tools);
            File.WriteAllText(filePath, content);
            keepFiles.Add(Path.GetFullPath(filePath));
        }

        foreach (var existing in Directory.EnumerateFiles(_paths.McpShadowDirectory, "*.md"))
        {
            var fullPath = Path.GetFullPath(existing);
            if (!keepFiles.Contains(fullPath))
                File.Delete(existing);
        }

        var layerContent = BuildToolIndexLayer(summaries);
        File.WriteAllText(_paths.ToolIndexShadowPath, layerContent);

        _logger.LogInformation(
            "Wrote MCP shadow catalogs ({ServerCount} servers) to {ShadowPath}",
            summaries.Count,
            _paths.McpShadowDirectory);

        return layerContent;
    }

    private string BuildToolIndexLayer(IReadOnlyList<McpServerSummary> summaries)
    {
        var index = _toolRegistry.GenerateCompressedIndex().TrimEnd();
        if (summaries.Count == 0)
            return index;

        var sb = new StringBuilder();
        sb.AppendLine(index);
        sb.AppendLine();
        sb.AppendLine("[shadow catalogs on disk]");
        sb.AppendLine("identity/tooling/shadow/mcp/<server>.md (system-generated)");
        return sb.ToString().TrimEnd();
    }

    private static string BuildServerCatalog(McpServerSummary summary, IReadOnlyList<INetclawTool> tools)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# MCP Shadow Catalog (System Generated)");
        sb.AppendLine();
        sb.AppendLine("Do not edit manually. This file is regenerated by netclawd startup.");
        sb.AppendLine();
        sb.AppendLine($"Server: {summary.ServerName}");
        sb.AppendLine($"Purpose: {summary.Description}");
        sb.AppendLine($"Tool Count: {summary.ToolCount}");
        sb.AppendLine();
        sb.AppendLine("## Tools");
        sb.AppendLine();

        foreach (var tool in tools)
        {
            var description = tool.Description.Length > 120
                ? tool.Description[..117] + "..."
                : tool.Description;
            var parameterHint = BuildParameterHint(tool);
            sb.AppendLine($"- {tool.Name} — {description}{parameterHint}");
        }

        if (tools.Count == 0)
            sb.AppendLine("- (no tools discovered)");

        return sb.ToString().TrimEnd();
    }

    private static string BuildParameterHint(INetclawTool tool)
    {
        if (tool.ParameterSchema.ValueKind != System.Text.Json.JsonValueKind.Object
            || !tool.ParameterSchema.TryGetProperty("properties", out var properties)
            || properties.ValueKind != System.Text.Json.JsonValueKind.Object)
        {
            return string.Empty;
        }

        var names = properties.EnumerateObject().Select(p => p.Name).ToList();
        if (names.Count == 0)
            return string.Empty;

        const int maxShown = 6;
        var shown = names.Take(maxShown).ToList();
        if (names.Count > maxShown)
            shown.Add($"+{names.Count - maxShown} more");

        return $" (params: {string.Join(", ", shown)})";
    }

    private static string ToSafeFileName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "unknown";

        var invalid = Path.GetInvalidFileNameChars();
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value.Trim())
        {
            if (invalid.Contains(ch))
            {
                sb.Append('-');
                continue;
            }

            if (char.IsWhiteSpace(ch))
            {
                sb.Append('-');
                continue;
            }

            sb.Append(ch);
        }

        var sanitized = sb.ToString().Trim('-');
        return string.IsNullOrEmpty(sanitized) ? "unknown" : sanitized;
    }
}
