// -----------------------------------------------------------------------
// <copyright file="PairingCodeService.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using System.Security.Cryptography;

namespace Netclaw.Daemon.Security;

/// <summary>
/// In-memory store for a single pending device pairing code.
///
/// <para>
/// Lifecycle:
/// <list type="bullet">
///   <item>Codes are generated by <c>netclaw daemon pair</c> via the SignalR hub.</item>
///   <item>Only one pending code exists at a time; generating a new code replaces the previous one.</item>
///   <item>Codes expire after 5 minutes and are consumed on first successful exchange.</item>
/// </list>
/// </para>
///
/// <para>Code format: 8 characters drawn from <c>23456789ABCDEFGHJKLMNPQRSTUVWXYZ</c>
/// (no ambiguous 0/O/1/I characters), displayed as <c>XXXX-XXXX</c>.</para>
/// </summary>
public sealed class PairingCodeService
{
    private static readonly char[] Alphabet =
        "23456789ABCDEFGHJKLMNPQRSTUVWXYZ".ToCharArray();

    private static readonly TimeSpan CodeTtl = TimeSpan.FromMinutes(5);

    private readonly TimeProvider _timeProvider;
    private readonly object _lock = new();
    private PendingCode? _pending;

    public PairingCodeService(TimeProvider timeProvider)
    {
        _timeProvider = timeProvider;
    }

    /// <summary>
    /// Generates a new pairing code, replacing any previously pending code.
    /// </summary>
    /// <returns>The formatted code (<c>XXXX-XXXX</c>) and its expiration time.</returns>
    public (string FormattedCode, DateTimeOffset ExpiresAt) GenerateCode()
    {
        // Use rejection sampling to avoid modulo bias over the 32-char alphabet.
        // The alphabet size (32) divides evenly into 256, so % 32 has no bias here;
        // but we use the standard "discard if >= threshold" pattern anyway for clarity.
        var rawBytes = RandomNumberGenerator.GetBytes(8);
        Span<char> chars = stackalloc char[8];
        for (var i = 0; i < 8; i++)
            chars[i] = Alphabet[rawBytes[i] % Alphabet.Length];

        var rawCode = new string(chars);
        var formatted = $"{rawCode[..4]}-{rawCode[4..]}";
        var expiresAt = _timeProvider.GetUtcNow().Add(CodeTtl);

        lock (_lock)
        {
            _pending = new PendingCode(rawCode, expiresAt);
        }

        return (formatted, expiresAt);
    }

    /// <summary>
    /// Attempts to consume the pending code.
    /// </summary>
    /// <param name="presentedCode">Code as presented by the remote client (with or without dash).</param>
    /// <returns><c>true</c> if the code matched and was not expired; the code is consumed on success.</returns>
    public bool TryConsume(string presentedCode)
    {
        var normalized = presentedCode.Replace("-", "", StringComparison.Ordinal).ToUpperInvariant();

        lock (_lock)
        {
            if (_pending is null)
                return false;

            if (_timeProvider.GetUtcNow() > _pending.ExpiresAt)
            {
                _pending = null;
                return false;
            }

            if (!string.Equals(normalized, _pending.RawCode, StringComparison.Ordinal))
                return false;

            _pending = null;
            return true;
        }
    }

    /// <summary>
    /// Returns the expiration time of the currently pending code,
    /// or <c>null</c> if no code is pending (or the code has expired).
    /// </summary>
    public DateTimeOffset? GetPendingExpiry()
    {
        lock (_lock)
        {
            if (_pending is null)
                return null;

            var now = _timeProvider.GetUtcNow();
            if (now > _pending.ExpiresAt)
            {
                _pending = null;
                return null;
            }

            return _pending.ExpiresAt;
        }
    }

    private sealed record PendingCode(string RawCode, DateTimeOffset ExpiresAt);
}
